services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fastapi_rabbitmq
    ports:
      - "5672:5672"     # AMQP (Celery)
      - "15672:15672"   # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  fastapi:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: amqp://user:password@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
      API_BASE_URL: http://web:8000
    networks:
      - default
    ports:
      - "8001:8001"
    depends_on:
      - rabbitmq

  fastapi_worker:
    build: .
    container_name: fastapi_worker
    command: celery -A app.tasks.celery_tasks.celery_app worker --loglevel=info
    volumes:
      - .:/app
    environment:
      CELERY_BROKER_URL: amqp://user:password@rabbitmq:5672//
      CELERY_RESULT_BACKEND: rpc://
      API_BASE_URL: http://web:8000
    networks:
      - default
    depends_on:
      - rabbitmq

networks:
  default:
    external:
      name: shared_network
